### PR TITLE
Fixed a Mega problem with status checker.

### PR DESCRIPTION
**Pull request by smartclash**
You've probably missed to write the word "ip" in fsockopen code. I've fixed it!

### CODE REVIEW

**Comment by jake-cryptic** [comment]
Ah yes I see, thank you

**Comment by smartclash** [comment]
@jake-cryptic I need some help. Can you please set this login form https://w3layouts.com/tab-widget-form-responsive-widget-template/ to work with the patchy? I tried but i was unsuccessful. Please do help me. I've added you as my collaborator to my repo. 

I also saw that you made some awesome changes to my repo (Smart Patch) when i was away. Sorry i didn't notice that. Thank you for your help.

**Comment by jake-cryptic** [comment]
@smartclash I will see what I can do but I'm doing my exams at the minute and so don't have as much free time as I'd like. Rest assured, as soon as my exams are over development on my github will skyrocket.

**Comment by smartclash** [comment]
@jake-cryptic Oops, sorry to disturb you. Take your time.

**Pull request merged**
